### ISSUE TITLE
[BUG]: friend page에 있는 내용이 무한 로딩되는 현상 

### ISSUE THREAD

**Issue by falconlee236** [22nd-Hoondong/Re-Frame#28]
## 설명
- friend page에 들어갔을 때 친구 목록이 나오지 않고 계속 로딩이 됩니다.

## 버그가 일어나는 상황
1. friend page에 들어감.
2. circleindicator만 나오고 아무것도 일어나지 않음

## 예상 동작
- 친구 목록이 나와야 합니다.

## 버그 화면
<img width="359" alt="스크린샷 2023-11-27 오후 11 15 20" src="https://github.com/22nd-Hoondong/Re-Frame/assets/52999093/8a6b5484-f1f2-42ea-a141-1cb9c39056d4">

**Comment by ldh019** [comment]
아마 목록이 없는 사람에 한해서 일어나는 상황일텐데 곧 수정하겠습니당
